import 'package:flutter/material.dart';

ThemeData lightMode = ThemeData(
  brightness: Brightness.light,
  colorScheme: ColorScheme.light(
    secondary: Colors.white70,
    outline: Colors.black54,
    primary: Colors.black87,
    surfaceTint: const Color(0xFFE6E6E6),
    surfaceBright: Colors.orange,
    secondaryContainer: Colors.grey.shade200,
    primaryContainer: const Color(0xFFE6E6E6),
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      letterSpacing: 1,
      color: Colors.black87,
      fontSize: 24,
      fontWeight: FontWeight.bold,
    ),
    displayMedium: TextStyle(
      letterSpacing: 1,
      color: Colors.black87,
      fontSize: 22,
      fontWeight: FontWeight.bold,
    ),
    displaySmall: TextStyle(
      letterSpacing: 1,
      color: Colors.black87,
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    headlineLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    headlineMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    headlineSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    titleLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.bold,
      color: Colors.black87,
    ),
    titleMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.bold,
      color: Colors.black87,
    ),
    titleSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.bold,
      color: Colors.black87,
    ),
    labelLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      color: Colors.black87,
    ),
    labelMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      color: Colors.black87,
    ),
    labelSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: Colors.black87,
    ),
    bodyLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      color: Colors.black87,
    ),
    bodyMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      color: Colors.black87,
    ),
    bodySmall: TextStyle(
      letterSpacing: 1,
      fontSize: 12,
      color: Colors.black87,
    ),
  ),
);

ThemeData darkMode = ThemeData(
  brightness: Brightness.dark,
  colorScheme: ColorScheme.dark(
    secondary: const Color(0xBE5A5A5A),
    outline: Colors.white70,
    primary: const Color(0xFFE6E6E6),
    surfaceTint: const Color(0xFFE6E6E6),
    surfaceBright: const Color(0xFFB36B00),
    secondaryContainer: Colors.grey.shade800,
    primaryContainer: Colors.black87,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      letterSpacing: 1,
      color: Color(0xFFE6E6E6),
      fontSize: 24,
      fontWeight: FontWeight.bold,
    ),
    displayMedium: TextStyle(
      letterSpacing: 1,
      color: Color(0xFFE6E6E6),
      fontSize: 22,
      fontWeight: FontWeight.bold,
    ),
    displaySmall: TextStyle(
      letterSpacing: 1,
      color: Color(0xFFE6E6E6),
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
    headlineLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    headlineMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    headlineSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: Colors.blue,
      decoration: TextDecoration.underline,
      decorationColor: Colors.blue,
    ),
    titleLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.bold,
      color: Color(0xFFE6E6E6),
    ),
    titleMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.bold,
      color: Color(0xFFE6E6E6),
    ),
    titleSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.bold,
      color: Color(0xFFE6E6E6),
    ),
    labelLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      color: Color(0xFFE6E6E6),
    ),
    labelMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      fontWeight: FontWeight.w600,
      color: Color(0xFFE6E6E6),
    ),
    labelSmall: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: Color(0xFFE6E6E6),
    ),
    bodyLarge: TextStyle(
      letterSpacing: 1,
      fontSize: 16,
      color: Color(0xFFE6E6E6),
    ),
    bodyMedium: TextStyle(
      letterSpacing: 1,
      fontSize: 14,
      color: Color(0xFFE6E6E6),
    ),
    bodySmall: TextStyle(
      letterSpacing: 1,
      fontSize: 12,
      color: Color(0xFFE6E6E6),
    ),
  ),
);
